import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,vi,test,expect} from "vitest";
import Home from "./page";
afterEach(()=>cleanup());
test("renders the Scenario Forge",()=>{vi.stubGlobal("fetch",vi.fn(()=>Promise.resolve({json:()=>Promise.resolve([])})));render(<Home/>);expect(screen.getByRole("heading",{name:/Scenario Forge/i})).toBeInTheDocument();expect(screen.getByRole("button",{name:/Inject Scenario/i})).toBeInTheDocument()});

test("opens the regression runner",()=>{vi.stubGlobal("fetch",vi.fn(()=>Promise.resolve({ok:true,json:()=>Promise.resolve([])})));render(<Home/>);fireEvent.click(screen.getByRole("button",{name:/Regression Runner/i}));expect(screen.getByRole("heading",{name:/Regression Runner/i})).toBeInTheDocument();expect(screen.getByRole("button",{name:/Run All Tests/i})).toBeInTheDocument();expect(screen.getByRole("button",{name:/Inject Known Defect/i})).toBeInTheDocument()});

test("renders the normalized evidence packet",async()=>{const scenario={key:"rapid-movement",id:"AML-SCN-002",version:1,family:"rapid-movement",case:"should-alert",control_id:"AML-RMF-001",name:"Rapid Movement",description:"Demo",expected_alert:true};const run={run_id:"run-1",scenario_key:"rapid-movement",control_id:"AML-RMF-001",control_version:1,seed:194028,counts:{transactions:4},expected:{alert:true,severity:"high"},actual:{alert:true,severity:"high"},result:"PASS",failure_reason:null,flows:[],alert:{alert_id:"alert-1",severity:"high",triggered_conditions:[],disposition:"Human review required"},evidence:{},enrichment:{job_id:"job-1",alert_id:"alert-1",status:"completed",started_at:"2026-08-15T12:00:00Z",completed_at:"2026-08-15T12:00:01Z",disposition:"Human review required",sources:[{source:"ofac",status:"completed",observed_at:"2026-08-15T12:00:00Z",provenance:{},error:null,findings:[{finding_id:"finding-1",finding_type:"sanctions_screening",outcome:"NO CANDIDATE",title:"Avery Williams",summary:"No candidate met the threshold.",score:null,source_record_id:null,details:{}}]}]}};const fetchMock=vi.fn().mockResolvedValueOnce({ok:true,json:()=>Promise.resolve([scenario])}).mockResolvedValueOnce({ok:true,json:()=>Promise.resolve([])}).mockResolvedValueOnce({ok:true,json:()=>Promise.resolve(run)});vi.stubGlobal("fetch",fetchMock);render(<Home/>);await waitFor(()=>expect(screen.getByRole("option",{name:"Rapid Movement"})).toBeInTheDocument());fireEvent.click(screen.getByRole("button",{name:/Inject Scenario/i}));expect(await screen.findByRole("heading",{name:/Normalized Evidence Packet/i})).toBeInTheDocument();expect(screen.getByText("NO CANDIDATE")).toBeInTheDocument();expect(screen.getByText(/makes no criminal determination/i)).toBeInTheDocument()});
