"use client";

import {useEffect,useMemo,useState} from "react";

type Scenario={key:string;id:string;version:number;family:string;case:string;control_id:string;name:string;description:string;expected_alert:boolean};
type Control={id:string;name:string;version:number;enabled:boolean;owner:string;description:string;severity:string;evaluator:string;scenario_coverage:string[]};
type Flow={source:string;destination:string;amount:number;currency:string};
type Run={run_id:string;scenario_key:string;control_id:string;control_version:number;seed:number;counts:Record<string,number>;expected:{alert:boolean;severity:string|null};actual:{alert:boolean|null;severity:string|null};result:"PASS"|"FAIL"|"UNTESTED";failure_reason:string|null;flows:Flow[];alert:null|{severity:string;triggered_conditions:string[];disposition:string};evidence:Record<string,unknown>};
type Regression={batch_id:string;seed:number;days:number;total:number;passed:number;failed:number;untested:number;coverage:number;mutation:null|{description:string};results:Run[]};
type View="Scenario Forge"|"Scenario Library"|"Control Management"|"Regression Runner";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";

export default function Home(){
  const [scenarios,setScenarios]=useState<Scenario[]>([]),[controls,setControls]=useState<Control[]>([]);
  const [selected,setSelected]=useState("rapid-movement"),[seed,setSeed]=useState(194028);
  const [view,setView]=useState<View>("Scenario Forge"),[busy,setBusy]=useState(false);
  const [run,setRun]=useState<Run|null>(null),[regression,setRegression]=useState<Regression|null>(null);
  const [error,setError]=useState("");
  async function load(){try{const [scenarioResponse,controlResponse]=await Promise.all([fetch(`${API}/api/v1/scenarios`),fetch(`${API}/api/v1/controls`)]);if(!scenarioResponse.ok||!controlResponse.ok)throw new Error();setScenarios(await scenarioResponse.json());setControls(await controlResponse.json())}catch{setError("API unavailable — start Docker Compose.")}}
  useEffect(()=>{void load()},[]);
  async function inject(){setBusy(true);setRun(null);setError("");try{const response=await fetch(`${API}/api/v1/scenarios/${selected}/runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seed,days:30})});if(!response.ok)throw new Error("Scenario execution failed");setRun(await response.json())}catch(e){setError(e instanceof Error?e.message:"Unknown error")}finally{setBusy(false)}}
  async function runAll(intentional=false){setBusy(true);setRegression(null);setError("");try{const endpoint=intentional?"intentional-regression":"";const response=await fetch(`${API}/api/v1/regression-runs/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seed,days:30})});if(!response.ok)throw new Error("Regression execution failed");setRegression(await response.json())}catch(e){setError(e instanceof Error?e.message:"Unknown error")}finally{setBusy(false)}}
  async function toggle(control:Control){setError("");try{const response=await fetch(`${API}/api/v1/controls/${control.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:!control.enabled})});if(!response.ok)throw new Error("Control update failed");const updated:Control=await response.json();setControls(items=>items.map(item=>item.id===updated.id?updated:item))}catch(e){setError(e instanceof Error?e.message:"Unknown error")}}
  const scenario=scenarios.find(item=>item.key===selected);
  const health=regression?Math.round(regression.passed/regression.total*100):run?.result==="PASS"?100:null;
  return <main>
    <header><div><span className="mark">◆</span><strong>SCRATCHLAB</strong><small>FINANCIAL CRIME CONTROL CENTER</small></div><div className="bank">DEMO BANK <i/> SYNTHETIC</div></header>
    <section className="metrics"><Metric label="CONTROL HEALTH" value={health===null?"—":`${health}%`}/><Metric label="ACTIVE CONTROLS" value={`${controls.filter(c=>c.enabled).length}/${controls.length||"—"}`}/><Metric label="TEST COVERAGE" value={regression?`${regression.coverage}%`:`${scenarios.length} CASES`}/><Metric label="LAST TEST RUN" value={run||regression?"JUST NOW":"NOT RUN"}/></section>
    <div className="shell"><nav>{(["Scenario Forge","Scenario Library","Control Management","Regression Runner"] as View[]).map(item=><button className={view===item?"active":""} onClick={()=>setView(item)} key={item}><span>{view===item?"◆":"◇"}</span>{item}</button>)}<div className="navSoon">COMING NEXT</div>{["Investigations","Entity Graph","Evidence Vault","Data Sources"].map(item=><div key={item}><span>◇</span>{item}</div>)}</nav>
      <section className="content"><div className="eyebrow">MILESTONE 02 / TESTING PLATFORM</div>{view==="Scenario Forge"&&<Forge scenarios={scenarios} selected={selected} setSelected={setSelected} seed={seed} setSeed={setSeed} scenario={scenario} busy={busy} inject={inject} run={run}/>} {view==="Scenario Library"&&<Library scenarios={scenarios}/>} {view==="Control Management"&&<Controls controls={controls} toggle={toggle}/>} {view==="Regression Runner"&&<Regress seed={seed} setSeed={setSeed} busy={busy} runAll={runAll} summary={regression}/>} {error&&<p className="error globalError">{error}</p>}<footer>ALL ENTITIES AND TRANSACTIONS ARE SYNTHETIC <span>•</span> HUMAN REVIEW REQUIRED <span>•</span> NO CRIMINAL DETERMINATIONS</footer></section>
    </div>
  </main>
}

function Forge({scenarios,selected,setSelected,seed,setSeed,scenario,busy,inject,run}:{scenarios:Scenario[];selected:string;setSelected:(value:string)=>void;seed:number;setSeed:(value:number)=>void;scenario?:Scenario;busy:boolean;inject:()=>void;run:Run|null}){return <><h1>Scenario Forge</h1><p className="lede">Inject deterministic synthetic behavior. Observe the control. Prove the outcome.</p><div className="grid"><article className="panel forge"><div className="panelTitle"><span>SCENARIO PARAMETERS</span><em>LIVE ENGINE</em></div><label>Scenario<select value={selected} onChange={e=>setSelected(e.target.value)}>{scenarios.map(s=><option value={s.key} key={s.key}>{s.name}</option>)}</select></label><div className="twocol"><label>Dataset seed<input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><label>Duration<input value="30 DAYS" disabled/></label></div><div className="scenarioInfo"><span>EXPECTED CONTROL</span><strong>{scenario?.control_id??"LOADING"} / {scenario?.expected_alert?"ALERT":"NO TRIGGER"}</strong><p>{scenario?.description??"Loading scenario library…"}</p></div><button onClick={inject} disabled={busy}>{busy?<><b className="spinner"/>PROCESSING SYNTHETIC ACTIVITY</>:"INJECT SCENARIO  →"}</button></article><article className="panel activity"><div className="panelTitle"><span>TRANSACTION FLOW</span><em>{run?`${run.counts.transactions} TX`:"AWAITING RUN"}</em></div>{!run?<Empty text="Choose a scenario and execute the control test."/>:<div className="flows">{run.flows.length?run.flows.map((flow,i)=><div className="flow" key={i}><span>{flow.source}</span><div><b>${flow.amount.toLocaleString()}</b><i>━━━━━━▶</i></div><span>{flow.destination}</span></div>):<Empty text="No control-relevant transactions were produced."/>}</div>}</article></div>{run&&<RunResult run={run}/>}</>}

function Library({scenarios}:{scenarios:Scenario[]}){const families=useMemo(()=>Array.from(new Set(scenarios.map(s=>s.family))),[scenarios]);return <><h1>Scenario Library</h1><p className="lede">Paired positive and negative tests protect detection and false-positive behavior.</p><div className="library">{families.map(family=><article className="scenarioCard" key={family}><div><span>SCENARIO FAMILY</span><h2>{family.replaceAll("-"," ")}</h2></div>{scenarios.filter(s=>s.family===family).map(s=><div className="case" key={s.key}><b className={s.expected_alert?"alertCase":"cleanCase"}>{s.expected_alert?"SHOULD ALERT":"SHOULD NOT ALERT"}</b><strong>{s.name}</strong><small>{s.control_id} · {s.id}@{s.version}</small><p>{s.description}</p></div>)}</article>)}</div></>}

function Controls({controls,toggle}:{controls:Control[];toggle:(control:Control)=>void}){return <><h1>Control Management</h1><p className="lede">Validated, versioned YAML definitions with independently persisted runtime state.</p><div className="controlTable"><div className="tableHead"><span>CONTROL</span><span>OWNER / COVERAGE</span><span>SEVERITY</span><span>STATE</span></div>{controls.map(control=><article key={control.id}><div><strong>{control.id} <small>v{control.version}</small></strong><p>{control.name}</p></div><div><strong>{control.owner}</strong><p>{control.scenario_coverage.length} mapped tests</p></div><b className={`severity ${control.severity}`}>{control.severity}</b><button className={control.enabled?"toggle enabled":"toggle"} onClick={()=>toggle(control)}><i/>{control.enabled?"ENABLED":"DISABLED"}</button><p className="controlDescription">{control.description}</p></article>)}</div></>}

function Regress({seed,setSeed,busy,runAll,summary}:{seed:number;setSeed:(value:number)=>void;busy:boolean;runAll:(intentional?:boolean)=>void;summary:Regression|null}){return <><h1>Regression Runner</h1><p className="lede">Execute every mapped test and isolate control regressions with reproducible evidence.</p><div className="runner"><article className="panel runConfig"><div className="panelTitle"><span>RUN CONFIGURATION</span><em>{busy?"EXECUTING":"READY"}</em></div><label>Dataset seed<input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><button onClick={()=>runAll(false)} disabled={busy}>RUN ALL TESTS →</button><button className="dangerButton" onClick={()=>runAll(true)} disabled={busy}>INJECT KNOWN DEFECT</button><p>The defect is ephemeral. It raises AML-RMF-001&apos;s threshold for one batch and never changes the active control.</p></article><article className="panel summaryPanel">{!summary?<Empty text="Run the suite to calculate control coverage."/>:<><div className="summaryHero"><div><span>COVERAGE</span><strong>{summary.coverage}%</strong></div><div className="donut" style={{"--coverage":`${summary.coverage*3.6}deg`} as React.CSSProperties}>{summary.passed}/{summary.total}</div></div><div className="summaryCounts"><b className="pass">PASS <strong>{summary.passed}</strong></b><b className="fail">FAIL <strong>{summary.failed}</strong></b><b className="untested">UNTESTED <strong>{summary.untested}</strong></b></div>{summary.mutation&&<div className="mutation">⚠ INTENTIONAL REGRESSION<br/><span>{summary.mutation.description}</span></div>}</>}</article></div>{summary&&<div className="results"><div className="tableHead"><span>RESULT</span><span>SCENARIO</span><span>CONTROL</span><span>EXPLANATION</span></div>{summary.results.map(item=><div className="resultRow" key={item.run_id}><b className={item.result.toLowerCase()}>{item.result}</b><span>{item.scenario_key}</span><span>{item.control_id} v{item.control_version}</span><span>{item.failure_reason??(item.actual.alert?`Alert / ${item.actual.severity}`:"Expected behavior observed")}</span></div>)}</div>}</>}

function RunResult({run}:{run:Run}){return <article className={`result ${run.result.toLowerCase()}`}><div className="resultIcon">{run.result==="PASS"?"✓":run.result==="FAIL"?"×":"—"}</div><div><span>CONTROL {run.actual.alert?"TRIGGERED":"NOT TRIGGERED"}</span><h2>{run.control_id} <small>v{run.control_version}</small></h2><p>{run.failure_reason??<>Expected: <b>{run.expected.alert?`ALERT / ${run.expected.severity?.toUpperCase()}`:"NO ALERT"}</b> &nbsp; Actual: <b>{run.actual.alert?`ALERT / ${run.actual.severity?.toUpperCase()}`:"NO ALERT"}</b></>}</p></div><div className="verdict">TEST RESULT<strong>{run.result}</strong><small>SEED {run.seed}</small></div></article>}
function Empty({text}:{text:string}){return <div className="empty"><div className="orbit">◎</div><strong>No results yet</strong><p>{text}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
