import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,expect,test,vi} from "vitest";
import CommandCenter from "./page";
import Forge from "./forge/page";
import Investigations from "./investigations/page";

afterEach(()=>{cleanup();vi.unstubAllGlobals()});
const response=(value:unknown)=>Promise.resolve({ok:true,json:()=>Promise.resolve(value)});

test("renders command-center metrics and source health",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response({control_health:94,test_coverage:87,open_cases:3,total_alerts:4,last_test_run:"2026-08-15T12:00:00Z",recent_failures:[],source_health:[{source:"ofac",status:"completed",observed_at:"2026-08-15T12:00:00Z",error:null}],transaction_activity:[]})));render(<CommandCenter/>);expect(screen.getByRole("heading",{name:"Command Center"})).toBeInTheDocument();expect(await screen.findByText("94%")).toBeInTheDocument();expect(screen.getByText(/ofac/i)).toBeInTheDocument();expect(screen.getByRole("link",{name:/Open Investigation Queue/i})).toHaveAttribute("href","/investigations")});

test("runs Forge with duration and links the created case",async()=>{const scenario={key:"rapid-movement",id:"AML-SCN-002",version:1,family:"rapid-movement",case:"should-alert",control_id:"AML-RMF-001",name:"Rapid Movement",description:"Demo",expected_alert:true};const run={run_id:"run-1",scenario_key:"rapid-movement",control_id:"AML-RMF-001",control_version:1,seed:194028,counts:{transactions:4},expected:{alert:true,severity:"high"},actual:{alert:true,severity:"high"},result:"PASS",failure_reason:null,flows:[],alert:{alert_id:"alert-1",severity:"high",triggered_conditions:[],disposition:"Human review required"},case_id:"case-1",evidence:{},enrichment:{job_id:"job-1",alert_id:"alert-1",status:"completed",started_at:"2026-08-15T12:00:00Z",completed_at:"2026-08-15T12:00:01Z",disposition:"Human review required",sources:[{source:"ofac",status:"completed",observed_at:"2026-08-15T12:00:00Z",provenance:{},error:null,findings:[{finding_id:"finding-1",finding_type:"sanctions_screening",outcome:"NO CANDIDATE",title:"Avery Williams",summary:"No candidate met the threshold.",score:null,source_record_id:null,details:{}}]}]}};const fetchMock=vi.fn().mockImplementationOnce(()=>response([scenario])).mockImplementationOnce(()=>response(run));vi.stubGlobal("fetch",fetchMock);render(<Forge/>);await waitFor(()=>expect(screen.getByRole("option",{name:"Rapid Movement"})).toBeInTheDocument());fireEvent.change(screen.getByLabelText("Duration"),{target:{value:"60"}});fireEvent.click(screen.getByRole("button",{name:/Inject Scenario/i}));expect(await screen.findByRole("heading",{name:/Normalized Evidence Packet/i})).toBeInTheDocument();expect(screen.getByRole("link",{name:/Open Investigation/i})).toHaveAttribute("href","/investigations/case-1");expect(fetchMock.mock.calls[1][1]?.body).toContain('"days":60')});

test("renders the persistent investigation queue",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response([{case_id:"case-1",case_number:"AML-2026-ABC12345",status:"open",severity:"high",customer_name:"Synthetic Customer",control_id:"AML-RMF-001",scenario_key:"rapid-movement",created_at:"2026-08-15T12:00:00Z",updated_at:"2026-08-15T12:00:00Z"}])));render(<Investigations/>);expect(await screen.findByText("AML-2026-ABC12345")).toBeInTheDocument();expect(screen.getByRole("link",{name:/AML-2026-ABC12345/i})).toHaveAttribute("href","/investigations/case-1")});
