export type Scenario={key:string;id:string;version:number;family:string;case:string;control_id:string;name:string;description:string;expected_alert:boolean};
export type Control={id:string;name:string;version:number;enabled:boolean;owner:string;description:string;severity:string;evaluator:string;scenario_coverage:string[]};
export type Finding={finding_id:string;finding_type:string;outcome:string;title:string;summary:string;score:number|null;source_record_id:string|null;details:Record<string,unknown>};
export type EvidenceSource={source:string;status:string;observed_at:string;provenance:Record<string,unknown>;error:string|null;findings:Finding[]};
export type EvidencePacket={job_id:string;alert_id:string;status:string;started_at:string;completed_at:string|null;disposition:string;sources:EvidenceSource[]};
export type Run={run_id:string;scenario_key:string;control_id:string;control_version:number;seed:number;counts:Record<string,number>;expected:{alert:boolean;severity:string|null};actual:{alert:boolean|null;severity:string|null};result:"PASS"|"FAIL"|"UNTESTED";failure_reason:string|null;flows:{source:string;destination:string;amount:number;currency:string}[];alert:null|{alert_id:string;severity:string;triggered_conditions:string[];disposition:string};enrichment:EvidencePacket|null;evidence:Record<string,unknown>;case_id:string|null};
export type Regression={batch_id:string;seed:number;days:number;total:number;passed:number;failed:number;untested:number;coverage:number;mutation:null|{description:string};results:Run[]};
export type CaseSummary={case_id:string;case_number:string;status:string;severity:string;customer_name:string;control_id:string;scenario_key:string;created_at:string;updated_at:string};
export type Note={note_id:string;author:string;body:string;created_at:string};
export type Transaction={transaction_id:string;source_account:string|null;destination_account:string|null;amount:number;currency:string;transaction_type:string;timestamp:string;geography:string};
export type CaseDetail=CaseSummary&{alert_id:string;run_id:string;account:Record<string,unknown>;customer:Record<string,unknown>;related_accounts:Record<string,unknown>[];transactions:Transaction[];triggered_conditions:string[];expected:Record<string,unknown>;actual:Record<string,unknown>;result:string;failure_reason:string|null;evidence:EvidencePacket|null;notes:Note[]};
export type Dashboard={control_health:number|null;test_coverage:number|null;open_cases:number;total_alerts:number;last_test_run:string|null;recent_failures:{run_id:string;scenario_key:string;control_id:string;reason:string|null;executed_at:string}[];source_health:{source:string;status:string;observed_at:string;error:string|null}[];transaction_activity:{date:string;count:number;volume:number}[]};
export type CaseGraph={case_id:string;nodes:{id:string;type:string;label:string;status:string|null;metadata:Record<string,unknown>}[];edges:{id:string;source:string;target:string;type:string;label:string;highlighted:boolean;metadata:Record<string,unknown>}[]};

export const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
export async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,init);if(!response.ok){let message="Request failed";try{message=(await response.json()).detail??message}catch{}throw new Error(message)}return response.json()}
