"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {Evidence} from "../../forge/page";
import {api,CaseDetail} from "../../types";

const tabs=["Overview","Transactions","Enrichment","Evidence","Test Result"] as const;
export default function Investigation(){const {caseId}=useParams<{caseId:string}>();const [item,setItem]=useState<CaseDetail|null>(null),[tab,setTab]=useState<(typeof tabs)[number]>("Overview"),[note,setNote]=useState(""),[error,setError]=useState("");function load(){api<CaseDetail>(`/api/v1/cases/${caseId}`).then(setItem).catch(e=>setError(e.message))}useEffect(load,[caseId]);async function status(value:string){try{setItem(await api<CaseDetail>(`/api/v1/cases/${caseId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:value})}))}catch(e){setError(e instanceof Error?e.message:"Update failed")}}async function addNote(e:React.FormEvent){e.preventDefault();if(!note.trim())return;try{await api(`/api/v1/cases/${caseId}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:note})});setNote("");load()}catch(e){setError(e instanceof Error?e.message:"Note failed")}}if(error&&!item)return <p className="error">{error}</p>;if(!item)return <p className="lede">Loading investigation…</p>;return <><div className="eyebrow">INVESTIGATION WORKSPACE</div><div className="caseTitle"><div><h1>{item.case_number}</h1><p className="lede">{item.customer_name} · {item.control_id}</p></div><div className="caseActions"><b className={`severity ${item.severity}`}>{item.severity}</b><select aria-label="Case status" value={item.status} onChange={e=>status(e.target.value)}><option value="open">OPEN</option><option value="in_review">IN REVIEW</option><option value="closed">CLOSED</option></select><Link href={`/graph/${item.case_id}`}>OPEN ENTITY GRAPH →</Link></div></div><nav className="tabs">{tabs.map(value=><button className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{value}</button>)}</nav>{tab==="Overview"&&<Overview item={item} note={note} setNote={setNote} addNote={addNote}/>} {tab==="Transactions"&&<Transactions item={item}/>} {tab==="Enrichment"&&<SourceSummary item={item}/>} {tab==="Evidence"&&(item.evidence?<Evidence packet={item.evidence}/>:<p className="lede">No enrichment packet is attached.</p>)} {tab==="Test Result"&&<TestResult item={item}/>} {error&&<p className="error">{error}</p>}</>}

function Overview({item,note,setNote,addNote}:{item:CaseDetail;note:string;setNote:(value:string)=>void;addNote:(e:React.FormEvent)=>void}){return <div className="investigationGrid"><article className="panel detailPanel"><h2>What happened</h2><dl><dt>Customer</dt><dd>{item.customer.synthetic_name as string}</dd><dt>Risk</dt><dd>{String(item.customer.risk_level).toUpperCase()}</dd><dt>Account</dt><dd>{String(item.account.account_id).slice(0,13)}</dd><dt>Relevant transactions</dt><dd>{item.transactions.length}</dd><dt>Expected monthly volume</dt><dd>${Number(item.customer.expected_monthly_volume).toLocaleString()}</dd></dl><h2>Why it alerted</h2><ul>{item.triggered_conditions.map(value=><li key={value}>{value.replaceAll("_"," ")}</li>)}</ul></article><article className="panel notesPanel"><h2>Analyst notes</h2><div className="notes">{item.notes.length?item.notes.map(value=><div key={value.note_id}><strong>{value.author}</strong><time>{new Date(value.created_at).toLocaleString()}</time><p>{value.body}</p></div>):<p className="lede">No notes recorded.</p>}</div><form onSubmit={addNote}><textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record an evidence-based observation…"/><button>ADD NOTE</button></form></article></div>}
function Transactions({item}:{item:CaseDetail}){return <div className="timeline">{item.transactions.map(tx=><article key={tx.transaction_id}><time>{new Date(tx.timestamp).toLocaleString()}</time><b>${tx.amount.toLocaleString()} {tx.currency}</b><span>{tx.source_account?.slice(0,8)??"EXTERNAL"} → {tx.destination_account?.slice(0,8)??"EXTERNAL"}</span><small>{tx.transaction_type} · {tx.geography}</small></article>)}</div>}
function SourceSummary({item}:{item:CaseDetail}){return <div className="sourceCards">{item.evidence?.sources.map(source=><article className="panel" key={source.source}><b className={source.status}>{source.status.toUpperCase()}</b><h2>{source.source.replaceAll("_"," ")}</h2><p>{source.findings.length} finding(s)</p><small>{source.error??new Date(source.observed_at).toLocaleString()}</small></article>)}</div>}
function TestResult({item}:{item:CaseDetail}){return <article className={`result ${item.result.toLowerCase()}`}><div className="resultIcon">{item.result==="PASS"?"✓":"×"}</div><div><span>CONTROL {item.actual.alert?"TRIGGERED":"NOT TRIGGERED"}</span><h2>{item.control_id}</h2><p>{item.failure_reason??"Expected and actual behavior matched."}</p></div><div className="verdict">TEST RESULT<strong>{item.result}</strong><small>{item.run_id.slice(0,8)}</small></div></article>}
