"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {Empty,Title} from "../page";
import {api,EvidencePacket,Run,Scenario} from "../types";

export default function Forge(){
  const [scenarios,setScenarios]=useState<Scenario[]>([]),[selected,setSelected]=useState("rapid-movement");
  const [seed,setSeed]=useState(194028),[days,setDays]=useState(30),[busy,setBusy]=useState(false);
  const [run,setRun]=useState<Run|null>(null),[error,setError]=useState("");
  useEffect(()=>{api<Scenario[]>("/api/v1/scenarios").then(setScenarios).catch(e=>setError(e.message))},[]);
  const scenario=scenarios.find(item=>item.key===selected);
  async function inject(){setBusy(true);setRun(null);setError("");try{setRun(await api<Run>(`/api/v1/scenarios/${selected}/runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seed,days})}))}catch(e){setError(e instanceof Error?e.message:"Scenario execution failed")}finally{setBusy(false)}}
  return <><div className="eyebrow">MILESTONE 04 / SCENARIO FORGE</div><h1>Scenario Forge</h1><p className="lede">Inject deterministic synthetic behavior. Observe the control. Follow the evidence into an investigation.</p><div className="grid"><article className="panel forge"><Title label="SCENARIO PARAMETERS" status={busy?"EXECUTING":"LIVE ENGINE"}/><label>Scenario<select value={selected} onChange={e=>setSelected(e.target.value)}>{scenarios.map(item=><option value={item.key} key={item.key}>{item.name}</option>)}</select></label><div className="twocol"><label>Dataset seed<input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><label>Duration<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[30,60,90].map(value=><option value={value} key={value}>{value} DAYS</option>)}</select></label></div><div className="scenarioInfo"><span>EXPECTED CONTROL</span><strong>{scenario?.control_id??"LOADING"} / {scenario?.expected_alert?"ALERT":"NO TRIGGER"}</strong><p>{scenario?.description??"Loading scenario library…"}</p></div><button onClick={inject} disabled={busy}>{busy?<><b className="spinner"/>PROCESSING SYNTHETIC ACTIVITY</>:"INJECT SCENARIO →"}</button></article><article className="panel activity"><Title label="TRANSACTION FLOW" status={run?`${run.counts.transactions} TX`:busy?"GENERATING":"AWAITING RUN"}/>{!run?<Empty text={busy?"Generating, evaluating, and enriching synthetic activity…":"Choose a scenario and execute the control test."}/>:<div className="flows">{run.flows.length?run.flows.map((flow,index)=><div className="flow replay" style={{animationDelay:`${index*120}ms`}} key={`${flow.source}-${flow.destination}-${index}`}><span>{flow.source}</span><div><b>${flow.amount.toLocaleString()}</b><i>━━━━━━▶</i></div><span>{flow.destination}</span></div>):<Empty text="No control-relevant transactions were produced."/>}</div>}</article></div>{run&&<><RunResult run={run}/>{run.case_id&&<Link className="primaryLink caseLink" href={`/investigations/${run.case_id}`}>OPEN INVESTIGATION →</Link>}{run.enrichment&&<Evidence packet={run.enrichment}/>}</>}{error&&<p className="error globalError">{error}</p>}</>
}

function RunResult({run}:{run:Run}){return <article className={`result ${run.result.toLowerCase()}`}><div className="resultIcon">{run.result==="PASS"?"✓":run.result==="FAIL"?"×":"—"}</div><div><span>CONTROL {run.actual.alert?"TRIGGERED":"NOT TRIGGERED"}</span><h2>{run.control_id} <small>v{run.control_version}</small></h2><p>{run.failure_reason??<>Expected: <b>{run.expected.alert?`ALERT / ${run.expected.severity?.toUpperCase()}`:"NO ALERT"}</b> &nbsp; Actual: <b>{run.actual.alert?`ALERT / ${run.actual.severity?.toUpperCase()}`:"NO ALERT"}</b></>}</p></div><div className="verdict">TEST RESULT<strong>{run.result}</strong><small>SEED {run.seed}</small></div></article>}

export function Evidence({packet}:{packet:EvidencePacket}){const labels:Record<string,string>={internal:"INTERNAL BANK",ofac:"OFAC SCREENING",fincen:"FINCEN INTELLIGENCE",mock_media:"MOCK ADVERSE MEDIA"};return <section className="evidencePanel"><div className="evidenceHead"><div><span>MILESTONE 03 / SCRATCHED EVIDENCE</span><h2>Normalized Evidence Packet</h2></div><b className={packet.status}>{packet.status.toUpperCase()}</b></div><p className="review">POTENTIAL MATCHES REQUIRE HUMAN REVIEW. SCRATCHLAB MAKES NO CRIMINAL DETERMINATION.</p><div className="evidenceGrid">{packet.sources.map(source=><article key={source.source} className={source.status}><header><strong>{labels[source.source]??source.source.toUpperCase()}</strong><span>{source.status.toUpperCase()}</span></header>{source.error&&<p className="sourceError">{source.error}</p>}{source.findings.length===0?<p className="noFindings">No relevant findings in the pinned snapshot.</p>:source.findings.map(finding=><div className="finding" key={finding.finding_id}><b>{finding.outcome}</b><strong>{finding.title}</strong><p>{finding.summary}</p>{finding.score!==null&&<small>MATCH SCORE {(finding.score*100).toFixed(1)}%</small>}</div>)}<footer>{new Date(source.observed_at).toLocaleString()} · PINNED SOURCE</footer></article>)}</div></section>}
