"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {applyNodeChanges,Background,Controls,Edge,MarkerType,MiniMap,Node,NodeChange,ReactFlow} from "@xyflow/react";
import {api,CaseGraph} from "../../types";

const colors:Record<string,string>={customer:"#47e0ae",account:"#68a8c0",sanctions_candidate:"#ff6b6b"};
export default function EntityGraph(){const {caseId}=useParams<{caseId:string}>();const [graph,setGraph]=useState<CaseGraph|null>(null),[nodes,setNodes]=useState<Node[]>([]),[selected,setSelected]=useState<Node|null>(null),[error,setError]=useState("");useEffect(()=>{api<CaseGraph>(`/api/v1/cases/${caseId}/graph`).then(value=>{setGraph(value);setNodes(layout(value))}).catch(e=>setError(e.message))},[caseId]);const edges=useMemo<Edge[]>(()=>graph?.edges.map(item=>({id:item.id,source:item.source,target:item.target,label:item.label,animated:item.highlighted,markerEnd:{type:MarkerType.ArrowClosed},style:{stroke:item.highlighted?"#47e0ae":"#49606a",strokeWidth:item.highlighted?2:1},labelStyle:{fill:"#a8bcc3",fontSize:9},data:item.metadata}))??[],[graph]);function change(changes:NodeChange[]){setNodes(value=>applyNodeChanges(changes,value))}return <><div className="eyebrow">CASE ENTITY GRAPH</div><div className="headingRow"><div><h1>Entity Graph</h1><p className="lede">Follow ownership, control-relevant flows, and candidate evidence.</p></div><Link className="secondaryLink" href={`/investigations/${caseId}`}>← BACK TO CASE</Link></div>{error&&<p className="error">{error}</p>}<div className="graphShell"><section className="graphCanvas">{graph&&<ReactFlow nodes={nodes} edges={edges} onNodesChange={change} onNodeClick={(_,node)=>setSelected(node)} fitView attributionPosition="bottom-left"><Background color="#213139" gap={24}/><MiniMap nodeColor={node=>colors[String(node.data.kind)]??"#78909b"} maskColor="#071015aa"/><Controls/></ReactFlow>}</section><aside className="evidenceDrawer">{selected?<><span>{String(selected.data.kind).replaceAll("_"," ")}</span><h2>{String(selected.data.label)}</h2>{Object.entries((selected.data.metadata??{}) as Record<string,unknown>).map(([key,value])=><div key={key}><b>{key.replaceAll("_"," ")}</b><p>{typeof value==="object"?JSON.stringify(value):String(value)}</p></div>)}</>:<><div className="orbit">◎</div><h2>Evidence drawer</h2><p>Select a node to inspect its profile or attached evidence.</p></>}</aside></div><div className="graphLegend">{Object.entries(colors).map(([kind,color])=><span key={kind}><i style={{background:color}}/>{kind.replaceAll("_"," ")}</span>)}<span><i className="flowKey"/>control-relevant flow</span></div></>}

function layout(graph:CaseGraph):Node[]{const counts:Record<string,number>={};return graph.nodes.map(item=>{const index=counts[item.type]??0;counts[item.type]=index+1;const column=item.type==="customer"?0:item.type==="account"?1:2;return {id:item.id,position:{x:80+column*330,y:70+index*150},data:{label:item.label,kind:item.type,status:item.status,metadata:item.metadata},style:{background:"#0d191f",border:`1px solid ${colors[item.type]??"#78909b"}`,borderRadius:2,color:"#e7f1ef",fontFamily:"inherit",fontSize:11,width:190,padding:14,boxShadow:`0 0 18px ${colors[item.type]??"#78909b"}22`}}})}
